server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 970389
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/test1?useSSL=false
    # druid初始化参数
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 等待连接时最大超时时间
    maxWait: 60000
    # 间隔多久检测需要关闭的连接，单位为毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中的最小生存时间，单位为毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    # 打开慢sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个dataSource的监控记录
    useGlobalDataSourceStat: true

mybatis:
  configuration:
    # 驼峰
    map-underscore-to-camel-case: true

# 输出MyBatis语句,trace会输出结果,debug只输出语句
logging:
  level:
    com:
      zx:
        springmybatis:
          dao: debug

